longpoll:
  # Токен доступа
  token: token
  # Версия
  version: 5.131
settings:
  # Время запуска (в cron формате, например: 0 0 6 * * *, будет срабатывать каждое утро в 6 часов)
  time: ''
  # Сообщения при запуске
  msg: ''
  # Картинки при запуске
  img: 'core/image.jpg'
  # ID чата (&sel=cID)
  chat: id